### ISSUE TITLE
Requests for new API variables

### ISSUE THREAD

**Issue by tudorached** [EasyBillApp/easybill#11]
1. **productPriceIncludesVAT** in **searchProducts** and **searchPC**
2. **clientPhone** in **searchClient**
3. **clientId** in **searchInvoice**
4. **invoiceType** in **searchInvoice**
5. **representativeName** in **searchInvoice**
6. **representativeIdetitySeries** in **searchInvoice**
7. **representativeIdetityNumber** in **searchInvoice**
8. **representativeIdetityEmittedBy** in **searchInvoice**
9. **representativeIdetityTransportType** in **searchInvoice**
10. **representativeIdetityTransportNumber** in **searchInvoice**
11. **clientAlreadyExists** in **addClient** (only when a client with the same CIF was already into the database)
12. **paymentDetails** in **getPayments**

**Comment by weballianz** [comment]
All done, except productPriceIncludesVAT in searchProducts and searchPC. It will be included in a future release.
