### ISSUE TITLE
addPayment_fct - 500 internal server error

### ISSUE THREAD

**Issue by tudorached** [EasyBillApp/easybill#19]
The API is not working:
https://apps.easybill.ro/cgi-bin/index.cgi?action=plugin&mode=api&sec=addPayment_fct

_Undefined subroutine &main::addPayment_fct called at /var/www/cgi-bin/index.cgi line 112._

**Comment by weballianz** [comment]
sorry, it should be: addpayment_fct

**Comment by weballianz** [comment]
Fixed
